sudo: false
language: node_js
cache:
  directories:
  - node_modules
codecov: true
env:
- NODE_ENV=development
matrix:
  fast_finish: true
install:
- NODE_ENV=development npm install
script:
- npm run lint
- npm run test -- --runInBand
- npm run coverage
deploy:
  skip_cleanup: true
  provider: npm
  email: epegzz@gmail.com
  api_key:
    secure: JNlU5fpCRhbpEVnmFbBopzRx5zpSqwmvpxY8gfacSg+GBxME9mIE3Uu2rnSE7GymeDyTse9HeBmd5TjrZ43FnI/RYyoJF6UEE/fVyFAaOGs/ID5H2DBtTFZ44VEznKHN8M5NVw/CDAUR4L3ySZYPATsMWRNGQHQRt/JnFggsqZ3Vlv5/8OpXDbWJNgibzgef9kLPkwwIDy25hiMuAVZ6RmgDqnq52kju48ugxLFLb2P2HgKLbVusGDGDZAmgPY5iIXGQx8EOWiW6UDBTiNQ0zVl/4mBRO4ZKSANIBt8IEia5X9tMNvgMXNR1QaYYdmto0K0H67ZLnahzSZoRXobNy2Y4272N/ilhCoJkp68/G0XW985O2oo3QElhjZkhvUem42IZfhd/tpnnEdTvpg7lvbylrTTV3wHtG6S/+baaoRE1uGzEJhDDo9JnPSM0rEWvXqFVvYfMy8eFoBw3fuGirDRm7V2J7V85rIIpPx4cRZPaeHaJziIhWHTjxJRhtZcqXmptUybOYRjlIlP0QS8MZg//kdEuXjoCzCyuJp/0Et+uq9IlSR6w+Txse7wlFD++go15sApVodSKo/KxkjI7nqUYZ0lnYOt+XRk9I5KiPWaKHtdeOgaYDNNPeabHJrx36HlCo4Bitt0yidCEWq4zlRvDJUUB6loh3odRMSnLaBs=
  on:
    tags: true
    repo: epegzz/node-scraper
